name: Dockerize

# When to run.
# In this case, manual only.
on:
  workflow_dispatch:

# Instructions on what to do.
# In this case, 'build' is the job and Ubuntu is the OS to run the job on.
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      USERNAME: jmqm
      REPOSITORY: vaultwarden_backup
      TAG: latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2.3.4

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Update README and description
        uses: peter-evans/dockerhub-description@v2.4.3
        with:
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }} # This action does not support tokens.
          repository: ${{ env.USERNAME }}/${{ env.REPOSITORY }}
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./README.md

      - name: Build image and push to Docker hub
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          push: true
          tags: ${{ env.USERNAME }}/${{ env.REPOSITORY }}:${{ env.TAG }}
